### ISSUE TITLE
Filesize limit of 2 bytes

### ISSUE THREAD

**Issue by xdiesp** [mp-s/edftools#1]
The tool cannot compile ASM files over a certain size limit. Look at this error: https://postimg.cc/mzrBsbBg
I ran some tests, and the limit seems to be 6553 commands in a single ASM.
Doesn't it sound like a 2 bytes limit? Could you push it to 4 bytes?

**Comment by mp-s** [comment]
Hi, if using 4 bytes jump instruction, the game may cause errors, such as the model does not render, or screen is only show sky box.
I will try to add 4-byte support, but if you want to use it, you should add "--jmp4" args

**Comment by xdiesp** [comment]
Thank you, but watch out: although large mission files now can be compiled, they are corrupted and unusable.
Here are two examples of ASM files: one small, which can be compiled with no problems; and one too large.

Small ASM: https://drive.google.com/file/d/1J2_d9eWoYy8tWAPoCgL3Xt-nr3WvAGMo/view?usp=sharing
Large ASM: https://drive.google.com/file/d/1gPItg6UuJW9gOGXXrqWAnxKvpuldym6h/view?usp=sharing

Previously, you could not compile the large one: now you can, but the compiled BVM is corrupted.
You can see how, if you compile the BVM back into ASM: the location\exit structure will be messed up, with many missing locations.

**Comment by mp-s** [comment]
fixed in 1.64

-----

This file,
>  Large ASM: https://drive.google.com/file/d/1gPItg6UuJW9gOGXXrqWAnxKvpuldym6h/view?usp=sharing

 has content without comments:
`  cuscall0    13     LoadResource(string resource, int)`

in line number:
```
8596
10326
10924
10956
10988
11020
```
So compilation will fail.

**Comment by xdiesp** [comment]
My bad, I must have uploaded one of those corrupted files. Here is a proper ASM that's too large: https://drive.google.com/file/d/1zmsdjf-yqWgKrniZcnR4fJkSvPEgTvDo/view?usp=sharing

**Comment by mp-s** [comment]
Nice, This file passes.

**Comment by xdiesp** [comment]
Yes ,thank you very much!
